version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tfjson2hcl
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
homebrew_casks:
  - repository:
      owner: winebarrel
      name: homebrew-tfjson2hcl
    homepage: https://github.com/winebarrel/tfjson2hcl
    description: tfjson2hcl converts heredoc JSON in Terraform files into jsonencode({...}) expressions.
    license: CC0-1.0
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfjson2hcl"]
          end
